version: '3.8'
services:
  db:
    image: mysql:8.0.39
    container_name: draw_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - draw_db_volumes:/var/lib/mysql
volumes:
  draw_db_volumes:
    name: draw_data