import type { Metadata } from 'next'
import './globals.css'
import SideBar from '@/components/SideBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className='flex-none'>
            <SideBar />
          </div>
          <div className='flex-auto'>{children}</div>
        </div>
      </body>
    </html>
  )
}
