import type { Metadata } from 'next'
import './globals.css'
import SideBar from '@/components/SideBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-row h-screen">
          <div className="fixed top-0 left-0">
            <SideBar />
          </div>
          <div className="fixed top-0 left-64 w-screen h-screen pb-40">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
